package com.example.maidy.ui.theme

import androidx.compose.ui.graphics.Color

// Maidy Color Palette
// Primary Colors
val MaidyBlue = Color(0xFF4A8BF5)
val MaidyTeal = Color(0xFF5A8B8A)
val MaidyDarkBlue = Color(0xFF2E3A59)

// Background Colors
val MaidyBackgroundLight = Color(0xFFF5F7FA)
val MaidyBackgroundWhite = Color(0xFFFFFFFF)
val MaidyBackgroundDark = Color(0xFF1E2A3A)

// Text Colors
val MaidyTextPrimary = Color(0xFF2E3A59)
val MaidyTextSecondary = Color(0xFF8F9BB3)
val MaidyTextLight = Color(0xFFFFFFFF)

// Border & Divider Colors
val MaidyBorderLight = Color(0xFFE4E9F2)
val MaidyBorderFocused = Color(0xFF4A8BF5)

// Button Colors
val MaidyButtonPrimary = Color(0xFF4A8BF5)
val MaidyButtonDisabled = Color(0x804A8BF5) // 50% opacity

// Tab & Toggle Colors
val MaidyTabSelected = Color(0xFFFFFFFF)
val MaidyTabUnselected = Color(0x00FFFFFF) // Transparent
val MaidyTabBackground = Color(0xFFf0f2f5)

// Status Colors
val MaidyErrorRed = Color(0xFFEF4444)
val MaidySuccessGreen = Color(0xFF10B981)

// Logo Background
val MaidyLogoBackground = Color(0xFF5A8B8A)

// Home Screen Colors
val HomeGreetingText = Color(0xFF1A1A1A)
val HomeSearchBackground = Color(0xFFF5F7FA)
val HomeSearchHint = Color(0xFF9CA3AF)
val HomeSearchIcon = Color(0xFF6B7280)
val HomeBookNowButton = Color(0xFF4A8BF5)
val HomeScheduleButton = Color(0xFFfeb74e)
val HomeScheduleButtonText = Color(0xFF1F2937)
val HomeSectionTitle = Color(0xFF1A1A1A)
val HomeBookingCardBackground = Color(0xFFFFFFFF)
val HomeBookingTitle = Color(0xFF1F2937)
val HomeBookingDetails = Color(0xFF6B7280)
val HomeStatusConfirmed = Color(0xFF10B981)
val HomeStatusConfirmedBg = Color(0xFFD1FAE5)
val HomeStatusInProgress = Color(0xFF3B82F6)
val HomeStatusInProgressBg = Color(0xFFDBEAFE)
val HomeStatusCompleted = Color(0xFF6B7280)
val HomeStatusCompletedBg = Color(0xFFF3F4F6)
val HomeCardBorder = Color(0xFFF3F4F6)
val HomeNotificationBadge = Color(0xFFEF4444)

// Booking Status Screen Colors
val BookingStatusBackground = Color(0xFFF8F9FB)
val BookingStatusCardBackground = Color(0xFFFFFFFF)
val BookingStatusServiceLabel = Color(0xFF6B7280)
val BookingStatusServiceValue = Color(0xFF1F2937)
val BookingStatusDateValue = Color(0xFF1F2937)
val BookingStatusPendingIcon = Color(0xFF9CA3AF)
val BookingStatusConfirmedIcon = Color(0xFF10B981)
val BookingStatusOnWayIcon = Color(0xFF3B82F6)
val BookingStatusInProgressIcon = Color(0xFFFBBF24)
val BookingStatusCompletedIcon = Color(0xFF6B7280)
val BookingStatusInactiveIcon = Color(0xFFE5E7EB)
val BookingStatusMapPlaceholder = Color(0xFFE5E7EB)
val BookingStatusMapBorder = Color(0xFFD1D5DB)
val BookingStatusMaidCardBackground = Color(0xFFFFFFFF)
val BookingStatusMaidCardBorder = Color(0xFFF3F4F6)
val BookingStatusMaidName = Color(0xFF1F2937)
val BookingStatusMaidInfo = Color(0xFF6B7280)
val BookingStatusStarRating = Color(0xFFFBBF24)
val BookingStatusContactButton = Color(0xFFDBEAFE)
val BookingStatusContactButtonText = Color(0xFF1E40AF)
val BookingStatusSOSButton = Color(0xFFFEE2E2)
val BookingStatusSOSButtonText = Color(0xFFB91C1C)
val BookingStatusCancelButton = Color(0xFFFEE2E2)
val BookingStatusCancelButtonText = Color(0xFFB91C1C)
val BookingStatusRateButton = Color(0xFFD1FAE5)
val BookingStatusRateButtonText = Color(0xFF047857)

// Emergency/SOS Screen Colors
val EmergencyScreenBackground = Color(0xFFDC2626) // Vibrant red
val EmergencyIconBorder = Color(0xFFFFFFFF)
val EmergencyIconBackground = Color(0xFFDC2626)
val EmergencyIconText = Color(0xFFFFFFFF)
val EmergencyTitleText = Color(0xFFFFFFFF)
val EmergencyDescriptionText = Color(0xFFFFFFFF)
val EmergencyCallButton = Color(0xFFFFFFFF)
val EmergencyCallButtonText = Color(0xFFDC2626)
val EmergencyCancelButton = Color(0x00FFFFFF) // Transparent
val EmergencyCancelButtonBorder = Color(0xFFFFFFFF)
val EmergencyCancelButtonText = Color(0xFFFFFFFF)

// Maid List Screen Colors
val MaidListBackground = Color(0xFFF8F9FB)
val MaidListTopBarBackground = Color(0xFFFFFFFF)
val MaidListTopBarTitle = Color(0xFF1F2937)
val MaidListBackIconTint = Color(0xFF1F2937)
val MaidListFilterChipSelectedBackground = Color(0xFF4A8BF5)
val MaidListFilterChipSelectedText = Color(0xFFFFFFFF)
val MaidListFilterChipSelectedBorder = Color(0xFF4A8BF5)
val MaidListFilterChipUnselectedBackground = Color(0xFFFFFFFF)
val MaidListFilterChipUnselectedText = Color(0xFF6B7280)
val MaidListFilterChipUnselectedBorder = Color(0xFFE5E7EB)
val MaidListFilterIconTint = Color(0xFF4A8BF5)
val MaidListCardBackground = Color(0xFFFFFFFF)
val MaidListCardBorder = Color(0xFFF3F4F6)
val MaidListMaidName = Color(0xFF1F2937)
val MaidListMaidRating = Color(0xFF1F2937)
val MaidListStarIcon = Color(0xFFFBBF24)
val MaidListRatingCount = Color(0xFF9CA3AF)
val MaidListServiceChipDeepCleaningBg = Color(0xFFDBEAFE)
val MaidListServiceChipDeepCleaningText = Color(0xFF1E40AF)
val MaidListServiceChipEcoFriendlyBg = Color(0xFFD1FAE5)
val MaidListServiceChipEcoFriendlyText = Color(0xFF047857)
val MaidListServiceChipPetFriendlyBg = Color(0xFFFED7AA)
val MaidListServiceChipPetFriendlyText = Color(0xFF92400E)
val MaidListServiceChipMoveInOutBg = Color(0xFFE9D5FF)
val MaidListServiceChipMoveInOutText = Color(0xFF6B21A8)
val MaidListSelectButtonBackground = Color(0xFF4A8BF5)
val MaidListSelectButtonText = Color(0xFFFFFFFF)
val MaidListViewDetailsButtonBackground = Color(0xFFF3F4F6)
val MaidListViewDetailsButtonText = Color(0xFF4B5563)

// Maid Profile Screen Colors
val MaidProfileBackground = Color(0xFFF8F9FB)
val MaidProfileNameText = Color(0xFF1F2937)
val MaidProfileRatingText = Color(0xFF1F2937)
val MaidProfileStarIcon = Color(0xFFFBBF24)
val MaidProfileReviewCount = Color(0xFF9CA3AF)
val MaidProfileTabSelected = Color(0xFF5A8B8A)
val MaidProfileTabUnselected = Color(0xFF6B7280)
val MaidProfileTabIndicator = Color(0xFF5A8B8A)
val MaidProfileContentBackground = Color(0xFFFFFFFF)
val MaidProfileAboutText = Color(0xFF4B5563)
val MaidProfileSectionTitle = Color(0xFF1F2937)
val MaidProfileServiceIcon = Color(0xFF5A8B8A)
val MaidProfileServiceText = Color(0xFF1F2937)
val MaidProfileServiceBackground = Color(0xFFF3F4F6)
val MaidProfileReviewerName = Color(0xFF1F2937)
val MaidProfileReviewDate = Color(0xFF9CA3AF)
val MaidProfileReviewText = Color(0xFF4B5563)
val MaidProfileReviewStar = Color(0xFFFBBF24)
val MaidProfilePriceLabel = Color(0xFF6B7280)
val MaidProfilePriceValue = Color(0xFF1F2937)
val MaidProfileBookButton = Color(0xFF5A8B8A)
val MaidProfileBookButtonText = Color(0xFFFFFFFF)
val MaidProfileBottomBarBackground = Color(0xFFFFFFFF)
val MaidProfileVerificationBadge = Color(0xFF3B82F6)

// Profile/Settings Screen Colors
val ProfileScreenBackground = Color(0xFFF8F9FB)
val ProfileHeaderBackground = Color(0xFFFFFFFF)
val ProfileImageBackground = Color(0xFFEBD5BD)
val ProfileImagePlaceholderIcon = Color(0xFF9E7E5C)
val ProfileEditIconBackground = Color(0xFF4A8BF5)
val ProfileEditIconTint = Color(0xFFFFFFFF)
val ProfileNameText = Color(0xFF1F2937)
val ProfileEmailText = Color(0xFF6B7280)
val ProfileFieldLabel = Color(0xFF6B7280)
val ProfileFieldBackground = Color(0xFFFFFFFF)
val ProfileFieldValue = Color(0xFF1F2937)
val ProfileSectionHeaderText = Color(0xFF1F2937)
val ProfileSettingItemBackground = Color(0xFFFFFFFF)
val ProfileSettingIconTint = Color(0xFF6B7280)
val ProfileSettingTitleText = Color(0xFF1F2937)
val ProfileSettingSubtitleText = Color(0xFF6B7280)
val ProfileSettingChevronTint = Color(0xFF9CA3AF)
val ProfileSwitchThumbChecked = Color(0xFFFFFFFF)
val ProfileSwitchTrackChecked = Color(0xFF4A8BF5)
val ProfileSwitchThumbUnchecked = Color(0xFFFFFFFF)
val ProfileSwitchTrackUnchecked = Color(0xFFE5E7EB)
val ProfileLogOutButtonBackground = Color(0xFFFCE7E7)
val ProfileLogOutButtonText = Color(0xFFDC2626)

// Booking Details Screen Colors
val BookingDetailsBackground = Color(0xFFF8F9FB)
val BookingDetailsTopBarBackground = Color(0xFFFFFFFF)
val BookingDetailsTitleText = Color(0xFF1F2937)
val BookingDetailsMaidName = Color(0xFF1F2937)
val BookingDetailsMaidRating = Color(0xFF1F2937)
val BookingDetailsStarIcon = Color(0xFFFBBF24)
val BookingDetailsReviewCount = Color(0xFF9CA3AF)
val BookingDetailsPriceText = Color(0xFF4A8BF5)
val BookingDetailsVerificationBadge = Color(0xFF3B82F6)
val BookingDetailsSectionTitle = Color(0xFF1F2937)
val BookingDetailsServiceCardSelectedBackground = Color(0xFF4A8BF5)
val BookingDetailsServiceCardSelectedBorder = Color(0xFF4A8BF5)
val BookingDetailsServiceCardSelectedTitle = Color(0xFFFFFFFF)
val BookingDetailsServiceCardSelectedSubtitle = Color(0xFFFFFFFF)
val BookingDetailsServiceCardUnselectedBackground = Color(0xFFFFFFFF)
val BookingDetailsServiceCardUnselectedBorder = Color(0xFFE5E7EB)
val BookingDetailsServiceCardUnselectedTitle = Color(0xFF1F2937)
val BookingDetailsServiceCardUnselectedSubtitle = Color(0xFF6B7280)
val BookingDetailsToggleBackground = Color(0xFFF0F2F5)
val BookingDetailsToggleSelected = Color(0xFFFFFFFF)
val BookingDetailsToggleTextSelected = Color(0xFF2E3A59)
val BookingDetailsToggleTextUnselected = Color(0xFF8F9BB3)
val BookingDetailsDateIcon = Color(0xFF4A8BF5)
val BookingDetailsDateLabel = Color(0xFF6B7280)
val BookingDetailsDateValue = Color(0xFF1F2937)
val BookingDetailsDateCardBackground = Color(0xFFFFFFFF)
val BookingDetailsTimeIcon = Color(0xFF4A8BF5)
val BookingDetailsTimeLabel = Color(0xFF6B7280)
val BookingDetailsTimeValue = Color(0xFF1F2937)
val BookingDetailsTimeCardBackground = Color(0xFFFFFFFF)
val BookingDetailsDaySelectorBackground = Color(0xFFFFFFFF)
val BookingDetailsDaySelectedBackground = Color(0xFF4A8BF5)
val BookingDetailsDaySelectedText = Color(0xFFFFFFFF)
val BookingDetailsDayUnselectedBackground = Color(0xFFFFFFFF)
val BookingDetailsDayUnselectedText = Color(0xFF6B7280)
val BookingDetailsDayUnselectedBorder = Color(0xFFE5E7EB)
val BookingDetailsNotesBackground = Color(0xFFFFFFFF)
val BookingDetailsNotesBorder = Color(0xFFE5E7EB)
val BookingDetailsNotesText = Color(0xFF1F2937)
val BookingDetailsNotesHint = Color(0xFF9CA3AF)
val BookingDetailsConfirmButton = Color(0xFF4A8BF5)
val BookingDetailsConfirmButtonText = Color(0xFFFFFFFF)

// Adjust Recurring Booking Screen Colors
val AdjustRecurringScreenBackground = Color(0xFFF8F9FB)
val AdjustRecurringTopBarBackground = Color(0xFFFFFFFF)
val AdjustRecurringTopBarTitle = Color(0xFF1F2937)
val AdjustRecurringBackIcon = Color(0xFF1F2937)
val AdjustRecurringCardBackground = Color(0xFFFFFFFF)
val AdjustRecurringSectionTitle = Color(0xFF1F2937)
val AdjustRecurringMaidName = Color(0xFF1F2937)
val AdjustRecurringMaidBorder = Color(0xFF4A8BF5)
val AdjustRecurringRatingStarColor = Color(0xFFFBBF24)
val AdjustRecurringRatingText = Color(0xFF6B7280)
val AdjustRecurringRateButton = Color(0xFF4A8BF5)
val AdjustRecurringRateButtonBg = Color(0xFFEBF5FF)
val AdjustRecurringFrequencySelectedBg = Color(0xFF4A8BF5)
val AdjustRecurringFrequencySelectedText = Color(0xFFFFFFFF)
val AdjustRecurringFrequencyUnselectedBg = Color(0xFFFFFFFF)
val AdjustRecurringFrequencyUnselectedText = Color(0xFF6B7280)
val AdjustRecurringFrequencyBorder = Color(0xFFE5E7EB)
val AdjustRecurringDaySelectedBg = Color(0xFF4A8BF5)
val AdjustRecurringDaySelectedText = Color(0xFFFFFFFF)
val AdjustRecurringDayUnselectedBg = Color(0xFFFFFFFF)
val AdjustRecurringDayUnselectedText = Color(0xFF6B7280)
val AdjustRecurringDayBorder = Color(0xFFE5E7EB)
val AdjustRecurringTimeIcon = Color(0xFF6B7280)
val AdjustRecurringTimeText = Color(0xFF1F2937)
val AdjustRecurringTimeCardBg = Color(0xFFFFFFFF)
val AdjustRecurringTimeCardBorder = Color(0xFFE5E7EB)
val AdjustRecurringServiceSelectedBg = Color(0xFF4A8BF5)
val AdjustRecurringServiceSelectedBorder = Color(0xFF4A8BF5)
val AdjustRecurringServiceSelectedText = Color(0xFF1F2937)
val AdjustRecurringServiceSelectedSubtext = Color(0xFF6B7280)
val AdjustRecurringServiceUnselectedBg = Color(0xFFFFFFFF)
val AdjustRecurringServiceUnselectedBorder = Color(0xFFE5E7EB)
val AdjustRecurringServiceUnselectedText = Color(0xFF1F2937)
val AdjustRecurringServiceUnselectedSubtext = Color(0xFF6B7280)
val AdjustRecurringServiceIconBg = Color(0xFFEBF5FF)
val AdjustRecurringServiceIcon = Color(0xFF4A8BF5)
val AdjustRecurringSaveButton = Color(0xFF4A8BF5)
val AdjustRecurringSaveButtonText = Color(0xFFFFFFFF)
